import {useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import MainLayout from "../layouts/MainLayout";
import {getDoctorProfile,updateDoctorProfile,uploadDoctorProfilePhoto} from "../services/doctorService";
const initial={name:"",email:"",phone:"",specialization:"",qualification:"",experience:"",nativeAddress:"",about:"",onlineConsultationFee:0,offlineConsultationFee:0,onlineAppointmentsEnabled:true,offlineAppointmentsEnabled:true};
export default function DoctorProfile(){const navigate=useNavigate();const[form,setForm]=useState(initial);const[image,setImage]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[msg,setMsg]=useState("");const[err,setErr]=useState("");
 useEffect(()=>{(async()=>{try{const d=(await getDoctorProfile()).doctor,u=d.user||{};setForm({name:u.name||"",email:u.email||"",phone:u.phone||"",specialization:d.specialization||"",qualification:d.qualification||"",experience:d.experience??"",nativeAddress:d.nativeAddress||"",about:d.about||"",onlineConsultationFee:d.onlineConsultationFee??0,offlineConsultationFee:d.offlineConsultationFee??d.consultationFee??0,onlineAppointmentsEnabled:d.onlineAppointmentsEnabled!==false,offlineAppointmentsEnabled:d.offlineAppointmentsEnabled!==false});setImage(u.profileImage?.url||"");}catch(e){setErr(e.response?.data?.message||"Unable to load doctor profile.");}finally{setLoading(false);}})();},[]);
 const ch=e=>{const{name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==="checkbox"?checked:value}));};
 const photo=async e=>{const file=e.target.files?.[0];if(!file)return;try{const d=await uploadDoctorProfilePhoto(file);setImage(d.profileImage?.url||"");setMsg("Profile photo updated.");}catch(x){setErr(x.response?.data?.message||"Unable to upload photo.");}};
 const save=async e=>{e.preventDefault();setSaving(true);setMsg("");setErr("");try{await updateDoctorProfile({...form,experience:form.experience===""?null:Number(form.experience),onlineConsultationFee:Number(form.onlineConsultationFee||0),offlineConsultationFee:Number(form.offlineConsultationFee||0)});setMsg("Profile and appointment settings saved successfully.");}catch(x){setErr(x.response?.data?.message||"Unable to save profile.");}finally{setSaving(false);}};
 if(loading)return <MainLayout><div className="max-w-5xl mx-auto py-10">Loading profile...</div></MainLayout>;
 return <MainLayout><div className="max-w-5xl mx-auto py-8 px-4"><div className="flex items-center justify-between mb-8"><div><h1 className="text-3xl font-bold">Doctor Profile</h1><p className="text-gray-500 mt-1">All profile fields below are optional unless your existing doctor account requires them.</p></div><button type="button" onClick={()=>navigate("/doctor/availability")} className="border px-4 py-2 rounded-lg">Availability & Appointment</button></div>
 {msg&&<div className="mb-4 rounded-lg bg-green-50 text-green-700 px-4 py-3">{msg}</div>}{err&&<div className="mb-4 rounded-lg bg-red-50 text-red-700 px-4 py-3">{err}</div>}
 <form onSubmit={save} className="space-y-6"><section className="bg-white rounded-2xl shadow p-6"><div className="flex items-center gap-5 mb-6">{image?<img src={image} alt="Doctor" className="w-24 h-24 rounded-full object-cover border"/>:<div className="w-24 h-24 rounded-full bg-blue-600 text-white flex items-center justify-center text-2xl font-bold">{form.name?.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()||"DR"}</div>}<div><h2 className="font-semibold text-lg">Profile Photo</h2><input type="file" accept="image/*" onChange={photo} className="mt-2 text-sm"/></div></div>
 <div className="grid md:grid-cols-2 gap-5"><Field label="Full Name" name="name" value={form.name} onChange={ch}/><Field label="Doctor Email ID" name="email" type="email" value={form.email} onChange={ch}/><Field label="Phone Number" name="phone" value={form.phone} onChange={ch}/><Field label="Specialization" name="specialization" value={form.specialization} onChange={ch}/><Field label="Education / Qualification" name="qualification" value={form.qualification} onChange={ch}/><Field label="Experience (years)" name="experience" type="number" min="0" value={form.experience} onChange={ch}/></div>
 <label className="block text-sm font-medium mt-5 mb-1">Native Address (optional)</label><textarea name="nativeAddress" value={form.nativeAddress} onChange={ch} rows="3" className="w-full border rounded-lg px-3 py-2"/><label className="block text-sm font-medium mt-5 mb-1">Description / About (optional)</label><textarea name="about" value={form.about} onChange={ch} rows="5" className="w-full border rounded-lg px-3 py-2"/></section>
 <section className="bg-white rounded-2xl shadow p-6"><h2 className="text-xl font-semibold">Appointment Settings</h2><p className="text-gray-500 mb-5">Enable the appointment modes you offer and set separate fees.</p><div className="grid md:grid-cols-2 gap-5"><Mode title="Offline Consultation" enabledName="offlineAppointmentsEnabled" feeName="offlineConsultationFee" enabled={form.offlineAppointmentsEnabled} fee={form.offlineConsultationFee} onChange={ch}/><Mode title="Online Consultation" enabledName="onlineAppointmentsEnabled" feeName="onlineConsultationFee" enabled={form.onlineAppointmentsEnabled} fee={form.onlineConsultationFee} onChange={ch}/></div></section>
 <div className="flex justify-end"><button disabled={saving} className="bg-blue-600 text-white px-7 py-3 rounded-lg disabled:opacity-60">{saving?"Saving...":"Save Changes"}</button></div></form></div></MainLayout>;
}
function Field({label,name,value,onChange,type="text",min}){return <div><label className="block text-sm font-medium text-gray-700 mb-1">{label} <span className="text-gray-400">(optional)</span></label><input name={name} type={type} min={min} value={value??""} onChange={onChange} className="w-full border rounded-lg px-3 py-2"/></div>}
function Mode({title,enabledName,feeName,enabled,fee,onChange}){return <div className="border rounded-xl p-5"><label className="flex items-center justify-between"><span className="font-semibold">{title}</span><input type="checkbox" name={enabledName} checked={enabled} onChange={onChange} className="w-5 h-5"/></label><label className="block text-sm font-medium mt-4 mb-1">Consultation Fee</label><input type="number" min="0" name={feeName} value={fee} onChange={onChange} className="w-full border rounded-lg px-3 py-2"/></div>}
